### ISSUE TITLE
Database/ table not rendering

### ISSUE THREAD

**Issue by Saroramath** [NotionX/react-notion-x#147]
Hi! The databases are not displaying anymore. This is from a page in the example https://react-notion-x-demo.transitivebullsh.it/collections-2fea615a97a7401c81be486e4eec2e94. 
There is supposed to be a table on the notion page not visible in deployed page. Does anyone know how to fix it?

**Comment by sozonome** [comment]
Confirmed, facing this issue too.

**Comment by spencerpauly** [comment]
The issue seems to be with the fetching of tables. Doesn't seem to be working anymore. I'm getting `NotionAPI collectionQuery error Response code 400 (Bad Request)` from the getPage() function.

**Comment by jozsefm** [comment]
Some of my tables just stopped to render a few hours ago.

**Comment by Dionid** [comment]
I've made some tests and dicovered:

1. Table rendering depends on how closer it's to start of the page
2. Problem happened in https://github.com/NotionX/react-notion-x/blob/master/packages/notion-client/src/notion-api.ts#L125 (`NotionAPI collectionQuery error Cannot read property 'type' of undefined`) because for some reason all collections will have `collectionInstance`, but not all of them will have `collectionView`

I've made PR to fix this https://github.com/NotionX/react-notion-x/pull/159

**Comment by jozsefm** [comment]
>     1. Table rendering depends on how closer it's to start of the page
I had the same observation! Looking forward for the fix! Thanks a lot in advance!

**Comment by transitive-bullshit** [comment]
Thanks to @Dionid's PR #159, I just released `notion-client` `v4.11.1` which should fix this issue.

@Dionid @jozsefm do you have a few IDs of notion pages this was affecting so I can add them to the regression test suite? I wasn't able to reproduce the issue myself locally. 

@Saroramath the demo was out-of-date and wasn't collections weren't working for an old issue that was fixed a month or two ago. It should be up-to-date now.

**Comment by jozsefm** [comment]
@transitive-bullshit Sadly I can't. My work is not public facing but maybe some details might give a hint. I have a table not showing up on a page with 4k words containing 99 toggle lists. Around the middle of the document it still displays but at the bottom it doesn't.

**Comment by transitive-bullshit** [comment]
@jozsefm no worries; let me know if you can produce a minimal repro. Also, does the fix in `v4.11.1` work or are you still experiencing the issue?

**Comment by Kevin-Bian21** [comment]
The notice ganllery view has been affected
![image](https://user-images.githubusercontent.com/64765636/141292841-2619c955-8c36-47e1-9a8b-a6f78205e480.png)
1. After verification, I found that the reason is that the Notion Gengllery view URL was changed。
2. It was like this before ：https://kevinbian.notion.site/6bf8801f4e9a4170bff4427860d88d20 ，But now it's like this ：https://kevinbian.notion.site/6bf8801f4e9a4170bff4427860d88d20?v=33f1a443d9d244549a0194dce374e59a，so this error that  "skipping missing collection view for block 6bf8801f-4e9a-4170-bff4-427860d88d20"  occurred.

**Comment by transitive-bullshit** [comment]
This should be fixed in the new v6. Please let me know if it's not.

**Comment by devdreams-program** [comment]
This is still not working for me with react-notion-x v 6.16.0. @transitive-bullshit do you have any idea? 
The error => skipping missing collection view for block ec3eda7b-5f68-408b-a1ba-93e09ebcdd26 

I'm on Nextjs

**Comment by ChanghyeonYoon** [comment]
@devdreams-program Same issue to me.

**Comment by quacrobat** [comment]
Has this regressed for anyone else but me?

running latest everything (updated/fresh install because error suddenly appeared on long running website without errors, so thought i'd try latest versions first).

skipping missing collection view for block 0b84ea49-34c6-... {
  collectionId: '.',
  collectionViewId: '...',
  collectionView: {
    id: '...',
    version: 14,
    type: 'gallery',
    name: 'Building & Space',
    format: {
      gallery_cover: [Object],
      collection_pointer: [Object],
      gallery_cover_size: 'medium',
      gallery_properties: [Array],
      gallery_cover_aspect: 'cover',
      hide_linked_collection_name: true
    },
    parent_id: '...',
    parent_table: 'block',
    alive: true,
    page_sort: [
 ...
    ],
    query2: { filter: [Object], aggregations: [Array] },
    space_id: '...'
  },
  collectionData: undefined,
  recordMap: {
    block: {
   ...
    },
    collection: {
 ...
    },
