### ISSUE TITLE
About Calendar view wIs there any progress?

### ISSUE THREAD

**Issue by ohjoij-ys** [NotionX/react-notion-x#413]
The question about Calendar view [(https://github.com/NotionX/react-notion-x/issues/36)](url)
at 2021.
I wonder if it's progressing

**Comment by MichaelCasaDev** [comment]
You can check out the PR progress here https://github.com/NotionX/react-notion-x/pull/369

I pushed few days ago some fixes and now it's waiting to be approved by @transitive-bullshit or @normdoow 🚀

**Comment by corytheinnocent** [comment]
Are we still receiving updates on this or should we start forking? :)
